# AI Code Ecosystem Japan - エージェント設定
# このファイルは各エージェントの役割と設定を定義します

agents:
  # 1. AIツール調査エージェント
  research:
    name: "AI Tool Research Agent"
    name_jp: "AIツール調査エージェント"
    description: "最新のAIコーディングツール情報を収集・分析"
    enabled: true
    schedule: 
      daily: "0 6,12,18 * * *"  # 6時、12時、18時に実行
      weekly_report: "0 9 * * MON"  # 月曜9時に週次レポート
    capabilities:
      - github_releases_monitoring
      - price_change_detection
      - feature_update_tracking
      - blog_post_scanning
    output:
      format: markdown
      path: /docs/updates/
      notify: true
    priority: high

  # 2. コンテンツ作成エージェント
  content:
    name: "Content Creator Agent"
    name_jp: "コンテンツ作成エージェント"
    description: "非エンジニア向けの分かりやすいコンテンツを作成"
    enabled: true
    triggers:
      - new_tool_detected
      - major_update_found
      - user_request
    templates:
      beginner: /agents/content/templates/beginner_guide.md
      comparison: /agents/content/templates/comparison.md
      use_case: /agents/content/templates/use_case.md
    style_guide:
      tone: friendly
      technical_level: beginner
      language: japanese
      use_examples: true
      include_visuals: true
    priority: high

  # 3. データ更新エージェント
  updater:
    name: "Data Updater Agent"
    name_jp: "データ更新エージェント"
    description: "サイトのデータを自動的に最新状態に維持"
    enabled: true
    schedule:
      daily: "0 2 * * *"  # 毎日深夜2時
      validation: "0 */12 * * *"  # 12時間ごとにリンクチェック
    tasks:
      - update_tool_prices
      - update_tool_versions
      - validate_external_links
      - update_data_ts
      - regenerate_sitemap
    backup:
      enabled: true
      retention_days: 30
    priority: medium

  # 4. 翻訳・ローカライゼーションエージェント
  translator:
    name: "Translation & Localization Agent"
    name_jp: "翻訳・ローカライゼーションエージェント"
    description: "英語コンテンツを高品質な日本語に翻訳"
    enabled: true
    sources:
      - official_docs
      - release_notes
      - blog_posts
    glossary_path: /agents/translator/glossary.json
    style:
      formality: neutral
      technical_accuracy: high
      cultural_adaptation: true
    review_required: true
    priority: medium

  # 5. コミュニティインサイトエージェント
  community:
    name: "Community Insights Agent"
    name_jp: "コミュニティ分析エージェント"
    description: "ユーザーニーズとトレンドを分析"
    enabled: true
    schedule:
      daily_scan: "0 10 * * *"
      weekly_analysis: "0 10 * * FRI"
    sources:
      - twitter: ["#AIコーディング", "#ClaudeCode", "#GitHubCopilot"]
      - reddit: ["r/programming", "r/artificial"]
      - qiita: ["ai-coding", "claude", "copilot"]
      - zenn: ["ai", "coding-assistant"]
    analysis:
      sentiment: true
      trending_topics: true
      common_issues: true
      feature_requests: true
    output:
      dashboard: true
      reports: /docs/community/insights/
    priority: low

# グローバル設定
global:
  notification:
    slack:
      enabled: false
      webhook_url: "${SLACK_WEBHOOK_URL}"
      channels:
        updates: "#ai-tools-updates"
        errors: "#ai-tools-errors"
    email:
      enabled: false
      recipients: []
    dashboard:
      enabled: true
      url: "/admin/agents"

  error_handling:
    retry_count: 3
    retry_delay: 300  # 5分
    alert_on_failure: true
    fallback_mode: manual

  logging:
    level: info
    path: /logs/agents/
    rotation: daily
    retention: 30  # days

  performance:
    max_concurrent_agents: 3
    timeout: 3600  # 1時間
    memory_limit: 512  # MB

# 環境別設定
environments:
  development:
    all_agents_enabled: false
    test_mode: true
    dry_run: true
    
  staging:
    all_agents_enabled: true
    test_mode: true
    dry_run: false
    
  production:
    all_agents_enabled: true
    test_mode: false
    dry_run: false